128/item download hooks
graasp/graasp-query-client pull request #129
Opened 2022-02-17 17:55 UTC by louisewang1

close #128

2022-02-21 11:02 UTC, pyphilia requested changes
Looks nice, I've added more comments. I guess some of them are also based on the backend implementation.

2022-02-21 11:02 UTC, pyphilia commented on test/constants.ts
> +}
As mentioned, it would be better to return the integer directly.

2022-02-21 19:27 UTC, louisewang1 commented on src/api/itemDownload.ts
> +      method: 'GET',
I tried it but with axios.get(), I could only pass in one parameter

2022-02-28 09:04 UTC, pyphilia approved these changes
All good for me, there's just some naming to change.

2022-02-28 09:04 UTC, pyphilia commented on src/config/keys.ts
> +  EXPORT_ZIP: 'downloadItem',
`exportZip`

2022-02-28 09:04 UTC, pyphilia commented on src/mutations/itemDownload.test.ts
> +describe('Download Item', () => {
Export Zip

2022-02-28 09:04 UTC, pyphilia commented on src/routines/itemDownload.ts
> +export const downloadItemRoutine = createRoutine('DOWNLOAD_ITEM');
Export zip?

2022-03-01 09:28 UTC, louisewang1 commented
I added a new mutation for update favorite items, so I requested a review for this PR again ;)

2022-03-04 13:20 UTC, pyphilia requested changes
Thanks for this PR! I've added my comments.

Is it possible to have tests for the new mutations?^^

2022-03-04 13:20 UTC, pyphilia commented on src/mutations/member.ts
> +      if (action === 'remove') {
As mentioned in the other PR, let's go with two mutations instead of this if clause.

2022-03-04 13:20 UTC, pyphilia commented on src/mutations/member.ts
> +      ) as Record<Member>;
I might be wrong but could you try `getQueryData<Record<Member>>`?

2022-03-04 13:20 UTC, pyphilia commented on src/mutations/member.ts
> +      notifier?.({ type: editMemberRoutine.FAILURE, payload: { error } });
I think you can create new routines dedicated to add / remove favorites.

2022-03-10 12:53 UTC, pyphilia approved these changes
👍

2022-03-10 17:04 UTC, merged