feat: add `useExportItemChat` hook
graasp/graasp-query-client pull request #203
Opened 2022-09-07 08:57 UTC by spaenleh

This PR adds a hook to get the export chat data from the backend.

closes #202

2022-09-09 08:38 UTC, pyphilia requested changes
As mentioned, I think it will be wiser to export the chat as a file directly from the back with a mutation. The logic could be included in the export data functions (export action, export as zip) as well. To discuss with @juancarlosfarah and @dialexo .

2023-02-13 08:31 UTC, spaenleh commented
I updated this PR with the deprecation of the immutable types exported by query-client.
These types were moved to `@graasp/sdk/frontend` in order to not duplicate the sources of typings.

closes #235

2023-02-13 10:21 UTC, pyphilia approved these changes
🍾

2023-02-13 10:21 UTC, pyphilia commented on src/hooks/chat.test.ts
> +    };
Have a builder function to create a mock message?

2023-02-16 17:13 UTC, merged