feat: handle favorite queries
graasp/graasp-query-client pull request #275
Opened 2023-05-23 12:44 UTC by morganridel

Based on branch `typeorm`

Related PRs:
 * core: https://github.com/graasp/graasp/pull/379
 * SDK: https://github.com/graasp/graasp-sdk/pull/164 
 * Builder: https://github.com/graasp/graasp-builder/pull/656

2023-06-14 09:40 UTC, spaenleh requested changes
🌳 Looks good, just a few comments, really like the simplicity of this since it has been de-coupled 👍

2023-06-14 09:40 UTC, spaenleh commented on src/api/itemFavorite.ts
> +  GET_FAVORITE_ITEMS_ROUTE, buildFavoriteItemRoute
Forgot to run prettier ?

2023-06-14 09:40 UTC, spaenleh commented on src/hooks/itemFavorite.test.ts
> +  describe('useLikesForItem', () => {
```suggestion
  describe('useFavoriteItems', () => {
```

2023-06-14 09:40 UTC, spaenleh commented on src/hooks/itemFavorite.test.ts
> +jest.spyOn(Cookies, 'get').mockReturnValue({ session: 'somesession' });
I guess we are not using JS cookies anymore

2023-06-14 09:40 UTC, spaenleh commented on src/mutations/itemFavorite.test.ts
> +jest.spyOn(Cookies, 'get').mockReturnValue({ session: 'somesession' });
Same here, I think we can get rid of this.

2023-06-14 09:40 UTC, spaenleh commented on src/mutations/itemFavorite.test.ts
> +    describe('useDeleteItemLike', () => {
```suggestion
    describe('useUnfavoriteItem', () => {
```

2023-06-14 09:40 UTC, spaenleh commented on src/mutations/itemFavorite.ts
> +    useUnfavoriteItem
I am not sure the difference between `useFavoriteItems` and `useFavoriteItem` will be clear. Maybe we could have `useAddFavoriteItem` and `useRemoveFavoriteItem` ? If you have a better idea feel free.

2023-06-14 09:40 UTC, spaenleh commented on test/constants.ts
> +    item: ITEM_1,
missing `createdAt`

2023-06-20 08:32 UTC, pyphilia approved these changes
LGTM I've left one comment so we can move forward to a new format for mutations.

2023-06-20 08:32 UTC, pyphilia commented on src/mutations/itemFavorite.ts
> +  queryClient.setMutationDefaults(MUTATION_KEYS.ADD_FAVORITE_ITEM, {
Do you think you could refactor this file given this new format? https://github.com/graasp/graasp-query-client/blob/main/src/mutations/itemTag.ts

2023-06-20 14:04 UTC, spaenleh approved these changes

2023-06-20 14:07 UTC, merged