279 add aggregate actions
graasp/graasp-query-client pull request #286
Opened 2023-06-22 07:31 UTC by rayacers

Add aggregate actions hook.

2023-06-23 12:55 UTC, spaenleh reviewed
Thank you for the PR, here are some comments and suggestions. 
I can't approve as I am not following this feature very closely. Looking forward to the aggregated graphs in Analytics !

2023-06-23 12:55 UTC, spaenleh commented on src/config/keys.ts
> +  args.requestedSampleSize,
Maybe you could use the object directly as second argument. React-query allows to use objects as keys [react-query docs](https://tanstack.com/query/v3/docs/react/guides/query-keys)

2023-06-23 12:55 UTC, spaenleh commented on src/hooks/action.test.ts
> +      view: 'builder',
Use `Context.Builder` from sdk.

2023-06-23 12:55 UTC, spaenleh commented on src/hooks/action.test.ts
> +      aggregateFunction: 'avg',
Do you support a fixed number of functions ? Can you put them in an enum or a const object to make it easier to reference ? This also means that you can type the argument more strictly (avoid "string" type if only certain values are allowed).

2023-06-23 12:55 UTC, spaenleh commented on src/hooks/action.ts
> +    },
This type is defined in 3 places, maybe factor it out ?

2023-06-26 12:31 UTC, pyphilia requested changes
I agree with everything Basile mentioned 👍

2023-08-15 08:18 UTC, closed without merging