fix: remove cookie when logout is confirmed, prevents logout loop
graasp/graasp-query-client pull request #63
Opened 2021-08-20 13:20 UTC by Julien-Torrent

This only update the user state when the backend confirms the logout

close #40

2021-08-27 23:38 UTC, juancarlosfarah approved these changes
I'm approving this as it makes total sense, but maybe @pyphilia wants to have a look Monday morning?

2021-08-30 08:38 UTC, pyphilia approved these changes

2021-08-30 08:40 UTC, pyphilia requested changes

2021-08-30 08:40 UTC, pyphilia commented on src/mutations/member.ts
>        const previousMember = queryClient.getQueryData(CURRENT_MEMBER_KEY);
Thanks for your changes! Perhaps remove the logic for `previousMember` as we are not using it anymore?

2021-08-30 09:20 UTC, pyphilia requested changes
Thanks for the changes. You'll need to remove line 29 too.

2021-08-30 11:54 UTC, merged