feat: add recycle bin endpoints
graasp/graasp-query-client pull request #67
Opened 2021-09-01 14:28 UTC by pyphilia

close #66

2021-09-07 10:09 UTC, Julien-Torrent requested changes

2021-09-07 10:09 UTC, Julien-Torrent commented on src/types.ts
> +  extra: any;
I think it is better to use `unknown`

2021-09-07 10:09 UTC, Julien-Torrent commented on test/utils.tsx
> +
If this is unused, we should delete it.

2021-09-09 22:33 UTC, juancarlosfarah requested changes
Looks good! Some minor comments. Agree with @Julien-Torrent. 👍

2021-09-09 22:33 UTC, juancarlosfarah commented on test/utils.tsx
> +
Agree.

2021-09-09 22:33 UTC, juancarlosfarah commented on src/mutations/item.ts
> +      // items themselves still exists but the path is different
exist*

2021-09-15 11:23 UTC, merged