feat: create use memberAction hook
graasp/graasp-query-client pull request #750
Opened 2024-05-01 14:53 UTC by LinaYahya

closes #745

2024-05-08 14:37 UTC, pyphilia approved these changes
LGTM! 🖍️

2024-05-08 14:37 UTC, pyphilia commented on src/config/keys.ts
> +export const buildMemberActionsFilteredByDateKey = (args: {
```suggestion
export const buildMemberActionsKey = (args: {
```
I think on longer term we will add more filters, so no need to be too precise.

2024-05-13 06:34 UTC, spaenleh requested changes

2024-05-13 06:34 UTC, spaenleh commented on src/api/action.ts
> +export const getMemberActionsFilteredByDate = async (
```suggestion
export const getMemberActions = async (
```

2024-05-13 06:34 UTC, spaenleh commented on src/api/routes.ts
> +export const buildGetMemberActions = (args: {
```suggestion
export const buildGetMemberActionsRoute = (args: {
```

2024-05-13 06:35 UTC, spaenleh commented on src/config/keys.ts
> +export const buildMemberActionsFilteredByDateKey = (args: {
Should this key be part of the `memberKeys.current()` ?

2024-06-03 10:25 UTC, spaenleh approved these changes
Changes look good to me, just some small nitpicks. You can merge once fixed !

2024-06-03 10:25 UTC, spaenleh commented on src/hooks/action.test.ts
> +      endDate: '2024-04-24T14:07:00.074Z',
Start and end date are the same, is this intentional ?

2024-06-03 10:25 UTC, spaenleh commented on src/hooks/action.test.ts
> +      const hook = () => hooks.useMemberActions(args);
Do you need to redefine the hook in each test ? can it be defined in the describe instead ?

2024-06-04 14:22 UTC, merged