deps: migrate Tanstack Query to v5
graasp/graasp-query-client pull request #892
Opened 2024-08-22 15:31 UTC by ReidyT

2024-08-23 07:18 UTC, spaenleh requested changes
Thank you fro tackling this issue and migrating to v5 !

I know this one is going to be a bit challenging. 
I have but some comments for the custom hook you created. I think we should move away from the useQuery.onSuccess completely and instead consider a better organisation of the keys for our use cases, alternatively there is also the possibility of using the `select` prop to transform the return of a query. [See the docs]
https://tanstack.com/query/v4/docs/framework/react/reference/useQuery#:~:text=select%3A%20(data%3A%20TData)%20%3D%3E%20unknown)

2024-08-23 07:18 UTC, spaenleh commented on src/.d.ts
Is the file supposed to be be called `.d.ts` ?

2024-08-23 07:18 UTC, spaenleh commented on src/utils/useOnDataChanged.ts
> +}
While I see why you implemented such a function, I think we will end-up with duplicated state if we use the hook more than once in the app as explained in the article you linked, see the [relevant section](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose#a-bad-api) about non-deduplicated call to onError.

2024-08-23 12:04 UTC, ReidyT commented
Just below is a diagram describing the behaviour of all the `useQuery` using `onSuccess`. I also include some `useQuery` which are the "default" queries for some cache, to have a better understanding of where and why some cache are manipulated manually. With this diagram, we could maybe reorganise our cache or the way we use query client.

```mermaid
graph LR
    subgraph "useMembers Hook"
        UseMembers["useQuery \n queryKey: memberKeys.many(ids)"] --> UseMembersSuccess
        UseMembersSuccess["onSuccess Callback"] --> IterateMembersData{Iterate over members.data}
        IterateMembersData -- member --> SetMemberData["queryClient.setQueryData()"]
    end
    SetMemberData --> MemberCache["Cache: memberKeys.single(id).content"]

    subgraph "useMember Hook"
        UseMember["useQuery \n queryKey: memberKeys.single(id).content"] --> MemberCache
    end

    subgraph "useManyItemPublishedInformations Hook"
        UseManyItemPublishedInfo["useQuery \n queryKey: itemKeys.many(args.itemIds).publishedInformation"] --> UseManyItemPublishedInfoSuccess
        UseManyItemPublishedInfoSuccess["onSuccess Callback"] --> IteratePublishedData{Iterate over publishedData.data}
        IteratePublishedData -- publishedInformation --> SetPublishedData["queryClient.setQueryData()"]
    end
    SetPublishedData --> PublishedInfoCache["Cache: itemKeys.single(id).publishedInformation"]

    subgraph "useItemPublishedInformation Hook"
        UseItemPublishedInfo["useQuery \n queryKey: itemKeys.single(args.itemId).publishedInformation"] --> PublishedInfoCache
    end

    subgraph "useItemsTags Hook"
        UseItemsTags["useQuery \n queryKey: itemKeys.many(ids).tags"] --> UseItemsTagsSuccess
        UseItemsTagsSuccess["onSuccess Callback"] --> IterateItemIds{Iterate over ids}
        IterateItemIds -- id --> GetItemTagFromData{Get item tag from data by id} -- itemTag --> SetTagsData["queryClient.setQueryData()"]
    end
    SetTagsData --> TagsCache["Cache: itemKeys.single(id).tags"]

    subgraph "useItemTags Hook"
        UseItemTags["useQuery \n queryKey: itemKeys.single(id).tags"] --> TagsCache
    end

    subgraph "useManyItemMemberships Hook"
        UseManyItemMemberships["useQuery \n queryKey: buildManyItemMembershipsKey(ids)"] --> UseManyItemMembershipsSuccess
        UseManyItemMembershipsSuccess["onSuccess Callback"] --> IterateMembershipIds{Iterate over ids}
        IterateMembershipIds -- id --> GetMembershipFromData{Get membership from data by id} -- membership --> SetMembershipsData["queryClient.setQueryData()"]
    end
    SetMembershipsData --> MembershipsCache["Cache: itemKeys.single(id).memberships"]

    subgraph "useItemMemberships Hook"
        UseItemMemberships["useQuery \n queryKey: itemKeys.single(id).memberships"] --> MembershipsCache
    end

    subgraph "useDescendants Hook"
      UseDescendants["useQuery \n queryKey: itemKeys.single(id).descendants(...)"] --> UseDescendantsSuccess
      UseDescendantsSuccess["onSuccess Callback"] --> IterateDescendantItems{Iterate over items}
      IterateDescendantItems -- item --> SetDescendantsData["queryClient.setQueryData()"]
      SetDescendantsData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end
    
    subgraph "useAccessibleItems Hook"
      UseAccessibleItems["useQuery \n queryKey: itemKeys.accessiblePage(...)"] --> UseAccessibleItemsSuccess
      UseAccessibleItemsSuccess["onSuccess Callback"] --> IterateAccessibleItems{Iterate over items}
      IterateAccessibleItems -- item --> SetAccessibleData["queryClient.setQueryData()"]
      SetAccessibleData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end

    subgraph "useInfiniteAccessibleItems Hook"
      UseInfiniteAccessibleItems["useInfiniteQuery \n queryKey: itemKeys.infiniteAccessible(...)"] --> UseInfiniteAccessibleItemsSuccess
      UseInfiniteAccessibleItemsSuccess["onSuccess Callback"] --> IteratePages{Iterate over pages}
      IteratePages -- page --> IterateAccessibleItemsFromPage{Iterate over items}
      IterateAccessibleItemsFromPage -- item --> SetInfiniteAccessibleData["queryClient.setQueryData()"]
      SetInfiniteAccessibleData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end
    
    subgraph "useChildren Hook"
      UseChildren["useQuery \n queryKey: itemKeys.single(id).children(...)"] --> UseChildrenSuccess
      UseChildrenSuccess["onSuccess Callback"] --> IterateChildrenItems{Iterate over items}
      IterateChildrenItems -- item --> SetChildrenData["queryClient.setQueryData()"]
      SetChildrenData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end

    subgraph "useParents Hook"
      UseParents["useQuery \n queryKey: itemKeys.single(id).parents"] --> UseParentsSuccess
      UseParentsSuccess["onSuccess Callback"] --> IterateParentsItems{Iterate over items}
      IterateParentsItems -- item --> SetParentsData["queryClient.setQueryData()"]
      SetParentsData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end

    subgraph "useItems Hook"
      UseItems["useQuery \n queryKey: itemKeys.many(ids).content"] --> UseItemsSuccess
      UseItemsSuccess["onSuccess Callback"] --> IterateItemsData{Iterate over items.data}
      IterateItemsData -- item --> SetItemsData["queryClient.setQueryData()"]
      SetItemsData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end

    subgraph "useRecycledItemsData Hook"
      UseRecycledItemsData["useQuery \n queryKey: memberKeys.current().recycled"] --> UseRecycledItemsDataSuccess
      UseRecycledItemsDataSuccess["onSuccess Callback"] --> IterateRecycledItemsData{Iterate over items}
      IterateRecycledItemsData -- item --> SetRecycledItemsData["queryClient.setQueryData()"]
      SetRecycledItemsData --> ItemSingleContentCache["Cache: itemKeys.single(id).content"]
    end

    style UseMembersSuccess fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style IterateMembersData fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style SetMemberData fill:#9cf,stroke:#333,stroke-width:2px,color:#000
    style MemberCache fill:#ff9,stroke:#333,stroke-width:2px,color:#000
    style UseMember fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseMembers fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseManyItemPublishedInfoSuccess fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style IteratePublishedData fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style SetPublishedData fill:#9cf,stroke:#333,stroke-width:2px,color:#000
    style PublishedInfoCache fill:#ff9,stroke:#333,stroke-width:2px,color:#000
    style UseItemPublishedInfo fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseManyItemPublishedInfo fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseItemsTags fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseItemsTagsSuccess fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style IterateItemIds fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style GetItemTagFromData fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style SetTagsData fill:#9cf,stroke:#333,stroke-width:2px,color:#000
    style TagsCache fill:#ff9,stroke:#333,stroke-width:2px,color:#000
    style UseItemTags fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseManyItemMemberships fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseManyItemMembershipsSuccess fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style IterateMembershipIds fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style GetMembershipFromData fill:#ccf,stroke:#333,stroke-width:2px,color:#000
    style SetMembershipsData fill:#9cf,stroke:#333,stroke-width:2px,color:#000
    style MembershipsCache fill:#ff9,stroke:#333,stroke-width:2px,color:#000
    style UseItemMemberships fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    style UseDescendants fill:#aaf,stroke:#333,stroke-width:2px,color:#000
    s [...]

2024-08-27 13:34 UTC, ReidyT commented
As we discussed this morning, we have to check that there is no performance drawbacks, but we'll probably be able to remove the `setQueryData` from the `useQuery`.

2024-09-13 09:17 UTC, ReidyT commented on src/.d.ts
I wasn't able to make it works without the `.d.ts` file (https://github.com/TanStack/query/discussions/2772#discussioncomment-7566892).

2024-09-18 14:38 UTC, pyphilia approved these changes
Thanks for this big refactor! I left some comments, let us know what are the next steps! 🦋

2024-09-18 14:38 UTC, pyphilia commented on src/hooks/invitation.ts
> +        typeError: getInvitationRoutine.FAILURE,
```suggestion
        routine: getInvitationRoutine,
```
I think this value is always available, so I think it makes sense to give the full routine, then you can get the failure from it?

2024-09-30 09:47 UTC, ReidyT commented on src/item/create/mutations.ts
> +      });
I think I'll create an issue and let it like that for now, but it could be interesting to refactor that in a second step.

2024-10-01 11:42 UTC, spaenleh approved these changes
Looks good !

2024-10-01 13:35 UTC, merged